import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "GramaKala",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "GramaKala | Empowering Rural Talent",
  description: "GramaKala is a platform to showcase and sell the rich skills and handmade products of rural India — from artisans, farmers, and local creators.",
  keywords: ["GramaKala", "rural talent", "village skills", "handmade", "India", "artisan products"],
  authors: [{ name: "GramaKala Team" }],
  openGraph: {
    title: "GramaKala | Empowering Rural Talent",
    description: "Discover authentic handmade products crafted by skilled artisans from Indian villages.",
    url: "https://gramakala.com",
    siteName: "GramaKala",
    images: [
      {
        url: "/logo.png", 
        width: 800,
        height: 600,
        alt: "GramaKala Logo",
      },
    ],
    locale: "en_IN",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
